# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08923d81b9ece11108fb9ed82da06e6452b8362ed568c3a483d898e760cffb491618e5cb43d12b721fff3709a000c5a05b5f448692c9a28863bcbfe659ae2ca3

test:
  secret_key_base: f4876f3f929b884a1f5aeeb862931f54ecb546b712e763f3cc8b786aaad1eef4189b799d87af6d534327f24d5ad08bb77138c9b2321c48dd4a8223c82c8190a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
